version: '3.8'

services:
  backend:
    build: ./Backend
    ports:
      - "3000:3000"
    volumes:
      - ./Backend:/app
    depends_on:
      - db

  frontend:
    build: ./Frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./database:/root/db
